#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — print it, and open it too if there's a browser to open it in.
# Over SSH to a headless Pi there usually isn't; the printed URL is the point.
open_url() {
  local url="$1"
  printf '  %s↗%s %s\n' "$GREEN" "$RESET" "$url"
  { if command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open   >/dev/null 2>&1; then open "$url"
    fi
  } >/dev/null 2>&1 || true
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "wrote ${#WRITTEN_ENV[@]} value(s): ${WRITTEN_ENV[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# ── Wizard-local helpers ──────────────────────────────────────────────────

ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# verify "what" cmd... — run a check, loop until it passes or the human gives
# up. Never fails the script; anything skipped lands in the closing summary.
verify() {
  local what="$1"; shift
  while true; do
    if "$@" >/dev/null 2>&1; then ok "$what"; return 0; fi
    fail "$what"
    if confirm "Fix it and retry the check?"; then continue; fi
    SKIPPED+=("$what")
    return 0
  done
}

# run "description" cmd... — show a command before running it, so the human
# can see exactly what the wizard is doing to their Pi.
run() {
  local what="$1"; shift
  printf '  %s$%s %s\n' "$DIM" "$RESET" "$*"
  if "$@"; then ok "$what"; else fail "$what — command exited non-zero"; pause "Enter to carry on anyway"; fi
}

PORT="${PORT:-3000}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_USER="$(id -un)"
ENV_TARGET=/etc/pr-arcade.env

# Secrets are staged in a private temp dir and installed to /etc/pr-arcade.env
# (0600) at the end of the env stage — never anywhere inside the repo. On a
# re-run we seed the staging file from /etc so existing values are offered back.
# TMPDIR is pointed at the same 0700 dir so write_env's own temp files (which
# briefly hold the token) land inside it and get wiped by the same trap.
TMPDIR="$(mktemp -d "${TMPDIR:-/tmp}/pr-arcade.XXXXXX")"
export TMPDIR
trap 'rm -rf "$TMPDIR"' EXIT
ENV_FILE="$TMPDIR/env"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"
if [[ -r "$ENV_TARGET" ]]; then cat "$ENV_TARGET" >"$ENV_FILE"; fi

install_env_file() {
  sudo install -m 600 -o "$SERVICE_USER" -g "$SERVICE_USER" "$ENV_FILE" "$ENV_TARGET"
  ok "installed $ENV_TARGET (0600, owner $SERVICE_USER)"
}

# HMAC via python3 with the secret in the environment — not on the command
# line, where any user on the box could read it out of ps.
sign_payload() {
  PRA_SECRET="$1" python3 -c 'import hmac,hashlib,os,sys
key = os.environb[b"PRA_SECRET"]
body = open(sys.argv[1], "rb").read()
print("sha256=" + hmac.new(key, body, hashlib.sha256).hexdigest())' "$2"
}

tailnet_hostname() {
  tailscale status --json 2>/dev/null |
    python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))'
}

banner "PR Arcade — Raspberry Pi setup"

sudo -v || true

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Raspberry Pi OS"
say "Run this wizard ON THE PI (over SSH is fine). If you haven't flashed the"
say "card yet, do this from your laptop first:"
step "Raspberry Pi Imager → Device: Raspberry Pi 4"
step "OS: Raspberry Pi OS (64-bit)  — the DESKTOP image, we need Chromium"
step "Storage: your SD card, then the gear/'Edit Settings' button:"
note "    • hostname: pr-arcade"
note "    • enable SSH, password or key auth"
note "    • username 'pi' + password, wifi + locale if not on ethernet"
step "Write the card, boot the Pi with the TV plugged in, then: ssh pi@pr-arcade.local"
say ""
say "Checking what we're running on..."
if [[ ! -f /etc/rpi-issue ]]; then
  warn "This doesn't look like Raspberry Pi OS."
  say "Flash the card as above, SSH into the Pi, clone the repo there and re-run"
  say "this script. Nothing has been changed."
  exit 1
fi
ok "Raspberry Pi OS"
# shellcheck source=/dev/null  # /etc/os-release only exists on the target
read -r OS_VERSION_ID OS_CODENAME < <(. /etc/os-release && echo "${VERSION_ID:-0} ${VERSION_CODENAME:-unknown}")
if [[ "$OS_VERSION_ID" =~ ^[0-9]+$ ]] && (( OS_VERSION_ID >= 12 )); then
  ok "Debian 12+ ($OS_CODENAME)"
else
  warn "older than Debian 12 (bookworm) — Node 22 and Chromium may not install cleanly"
  pause "Enter to try anyway"
fi
# shellcheck disable=SC2016  # deliberately evaluated inside the retried check
verify "desktop image (boots to graphical.target)" \
  bash -c '[[ "$(systemctl get-default)" == graphical.target ]]'
say ""
say "The kiosk needs the Pi to log into the desktop by itself after a power cut."
if grep -qs '^autologin-user=' /etc/lightdm/lightdm.conf; then
  ok "desktop autologin is configured"
else
  warn "desktop autologin not detected"
  if confirm "Turn it on now (raspi-config: boot to Desktop, autologin)?"; then
    run "autologin enabled" sudo raspi-config nonint do_boot_behaviour B4
  else
    SKIPPED+=("desktop autologin — sudo raspi-config nonint do_boot_behaviour B4")
  fi
fi
say ""
say "Screen blanking has to be off or the TV goes black after 10 minutes."
if confirm "Disable screen blanking now?"; then
  run "screen blanking disabled" sudo raspi-config nonint do_blanking 1
  note "(also switchable in Preferences → Raspberry Pi Configuration → Display)"
fi
pause "Enter for the package install"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Packages — Node 22, git, Chromium"
say "Installing everything the server and the kiosk need. Takes a few minutes."
if [[ "$(node -v 2>/dev/null || echo none)" == v22.* ]]; then
  ok "Node 22 already installed ($(node -v))"
else
  run "apt updated" sudo apt-get update
  run "prerequisites" sudo apt-get install -y ca-certificates curl gnupg git
  run "NodeSource repo added" \
    bash -c 'curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -'
  run "nodejs installed" sudo apt-get install -y nodejs
fi
# The desktop image already ships Chromium; this is a no-op there. unclutter
# hides the mouse pointer on the TV.
sudo apt-get install -y unclutter >/dev/null 2>&1 ||
  SKIPPED+=("unclutter (mouse pointer will show on the TV)")
if ! command -v chromium-browser >/dev/null 2>&1 && ! command -v chromium >/dev/null 2>&1; then
  sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium || true
fi
# shellcheck disable=SC2016  # deliberately evaluated inside the retried check
verify "node 22" bash -c '[[ "$(node -v)" == v22.* ]]'
verify "npm" command -v npm
verify "git" command -v git
verify "chromium" bash -c 'command -v chromium-browser || command -v chromium'
pause "Enter to join the tailnet"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Tailscale — join the tailnet"
say "Tailscale gives the Pi a stable HTTPS hostname for GitHub's webhooks"
say "(and SSH access to the Pi from anywhere) without buying a domain."
if ! command -v tailscale >/dev/null 2>&1; then
  run "tailscale installed" bash -c 'curl -fsSL https://tailscale.com/install.sh | sh'
fi
if tailscale status >/dev/null 2>&1; then
  ok "already logged in as $(tailnet_hostname 2>/dev/null || echo 'this node')"
else
  say "'tailscale up' will print a login URL. Open it on your laptop and"
  say "approve this machine, then come back here."
  sudo tailscale up --hostname=pr-arcade || true
fi
verify "tailscale is up" tailscale status
TS_HOST="$(tailnet_hostname 2>/dev/null || true)"
if [[ -z "${TS_HOST:-}" ]]; then
  ask TS_HOST "Couldn't read it — paste this node's full tailnet hostname (x.tailXXXX.ts.net):"
fi
if [[ -z "${TS_HOST:-}" ]]; then
  fail "no tailnet hostname"
  say "Without one there's no public URL for GitHub to deliver webhooks to."
  say "Get 'tailscale status' working, then re-run the wizard. Stopping here."
  exit 1
fi
ok "tailnet hostname: $TS_HOST"
pause "Enter to expose the server publicly"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Tailscale Funnel — public HTTPS for the webhook"
# Re-runs land here with the funnel already serving — nothing to do, skip the
# manual cert walk entirely.
if tailscale funnel status 2>/dev/null | grep -q "127.0.0.1:$PORT"; then
  ok "Funnel already serving https://$TS_HOST → 127.0.0.1:$PORT"
else
say "Funnel puts https://$TS_HOST on the public internet, forwarded to the"
say "server on port $PORT. It needs HTTPS certificates — enabled once per"
say "tailnet in the admin console. Both switches live on the DNS page:"
step "Open the DNS page:"
open_url "https://login.tailscale.com/admin/dns"
step "Under 'MagicDNS': if there's an 'Enable MagicDNS' button, click it"
note "    (already on for most tailnets — then there's nothing to click)"
step "Scroll down to 'HTTPS Certificates' → 'Enable HTTPS...' → confirm"
note "    This lets Tailscale mint Let's Encrypt certs for $TS_HOST."
pause "Enter when both are on — the next check mints a cert to prove it"
say "Requesting a certificate (the first mint can take a minute)..."
# Run the mint with its output VISIBLE — the errors are the diagnostics
# ("not enabled" = toggle not picked up yet, try 'sudo tailscale up'; ACME
# timeouts = Let's Encrypt is slow on the first mint, just retry).
CERT_DIR=$(mktemp -d)
while ! (cd "$CERT_DIR" && sudo tailscale cert "$TS_HOST"); do
  fail "cert mint failed — the message above says why"
  note "    'not enabled': wait a minute or run 'sudo tailscale up', then retry."
  note "    ACME/timeout: the first mint can be slow — just retry."
  if ! confirm "Retry the mint?"; then
    SKIPPED+=("HTTPS certificate for $TS_HOST (funnel will retry on first request)")
    break
  fi
done
[[ -f "$CERT_DIR/$TS_HOST.crt" ]] && ok "HTTPS certificates enabled — minted a cert for $TS_HOST"
say "Funnel also needs the 'funnel' node attribute in the tailnet policy."
step "If the funnel below refuses to start, Tailscale prints the exact link"
note "    and policy JSON to add — it's one paste in Access Controls:"
open_url "https://login.tailscale.com/admin/acls/file"
say "Starting the funnel in the background (survives reboots)..."
sudo tailscale funnel --bg "$PORT" || warn "funnel didn't start — read the message above"
verify "funnel is serving port $PORT" \
  bash -c "tailscale funnel status | grep -q '$PORT'"
fi
WEBHOOK_URL="https://$TS_HOST/webhook"
ok "webhook URL will be: $WEBHOOK_URL"
pause "Enter to set up the code"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The repo"
if git -C "$REPO_DIR" rev-parse --show-toplevel >/dev/null 2>&1; then
  ok "running from a checkout at $REPO_DIR"
else
  warn "this script isn't inside a git checkout"
  say "Clone the repo on the Pi and re-run the wizard from there:"
  note "  git clone <repo-url> ~/pr-arcade && ~/pr-arcade/deploy/setup-wizard.sh"
  exit 1
fi
say ""
say "deploy.sh pulls from this remote later, so git needs credentials that work"
say "without a human at the keyboard."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  run "git set up to use your gh login" gh auth setup-git
else
  say "No gh login on this Pi. For a private repo, pick one:"
  step "gh:         sudo apt-get install -y gh && gh auth login && gh auth setup-git"
  step "deploy key: ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''"
  note "            then add ~/.ssh/id_ed25519.pub as a deploy key under"
  note "            github.com/<owner>/<repo>/settings/keys, and make sure the"
  note "            remote is the ssh one (git remote set-url origin git@github.com:...)"
fi
# BatchMode/no-prompt so a missing credential fails the check instead of
# hanging on an invisible password prompt.
verify "git can reach the remote without prompting" \
  env GIT_TERMINAL_PROMPT=0 GIT_SSH_COMMAND='ssh -o BatchMode=yes' \
  git -C "$REPO_DIR" ls-remote --exit-code origin HEAD
say ""
run "dependencies installed" bash -c "cd '$REPO_DIR' && npm ci"
verify "node_modules present" test -d "$REPO_DIR/node_modules"
# The server reads the Tracked Repo list from config.json at startup and exits
# if it's missing — which looks like an invisible 5-second restart loop.
# config.json is gitignored (it names your repos and your team), so a fresh
# clone has only the example: copy it, then say so — the placeholder repos in
# it are not yours, and every step below works off this list.
if [[ ! -f "$REPO_DIR/config.json" ]]; then
  cp "$REPO_DIR/config.example.json" "$REPO_DIR/config.json"
  warn "created config.json from config.example.json — edit it before going further:"
  note "  trackedRepos      the repos whose activity feeds the board"
  note "  names             GitHub login -> first name, and the roster for clips"
  note "  devDeployWorkflow the deploy-to-dev workflow's file name"
  note "  newsFeedUrl       the RSS or Atom source for the bottom ticker"
  pause "Enter once you have edited $REPO_DIR/config.json"
fi
verify "config.json present (the Tracked Repo list)" test -f "$REPO_DIR/config.json"
# Read the list back rather than keeping a second copy in this script.
mapfile -t TRACKED_REPOS < <(
  python3 -c 'import json,sys; print("\n".join(json.load(open(sys.argv[1]))["trackedRepos"]))' \
    "$REPO_DIR/config.json"
)
if [[ ${#TRACKED_REPOS[@]} -eq 0 ]]; then
  # Also where a malformed config.json lands: the read above fails inside a
  # process substitution, which set -e does not catch, leaving the list empty.
  fail "config.json lists no trackedRepos — the webhook and test stages need it"
  exit 1
fi
ok "tracked repos: ${TRACKED_REPOS[*]}"
pause "Enter to create the secrets file"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Secrets — $ENV_TARGET"
say "Secrets live only in $ENV_TARGET (0600). Never in the repo."
WEBHOOK_SECRET="$(_existing GITHUB_WEBHOOK_SECRET || true)"
if [[ -n "$WEBHOOK_SECRET" ]]; then
  SECRET_IS_NEW=no
  ok "reusing the existing webhook secret (regenerating would break the hooks)"
else
  WEBHOOK_SECRET="$(openssl rand -hex 32)"
  SECRET_IS_NEW=yes
  ok "generated a new webhook secret (openssl rand -hex 32)"
fi
if [[ -n "$(_existing GITHUB_TOKEN || true)" ]]; then
  say ""
  ok "a GITHUB_TOKEN is already configured — just press Enter to keep it"
  note "if the board never names who's in dev, this token predates that feature:"
  note "add Repository permissions → Actions: Read-only to it and restart"
else
  say ""
  say "Now a fine-grained PAT, so the display can Backfill open PRs on boot:"
  open_url "https://github.com/settings/personal-access-tokens/new"
  step "Resource owner: the org that owns your Tracked Repos"
  step "Repository access: Only select repositories → projects-app, features, content"
  step "Repository permissions → Metadata: Read-only (it's mandatory)"
  step "Repository permissions → Pull requests: Read-only"
  step "Repository permissions → Issues: Read-only  (PR comments are issue comments)"
  step "Repository permissions → Actions: Read-only  (who last deployed to dev)"
  step "Generate token, then copy it."
fi
ask_secret GITHUB_TOKEN "Paste a token (input hidden; Enter keeps current / skips):"
say ""
if [[ -n "$(_existing POSTHOG_PERSONAL_API_KEY || true)" ]]; then
  ok "a POSTHOG_PERSONAL_API_KEY is already configured — just press Enter to keep it"
else
  say "Now a PostHog personal API key for the Weekly WAU Growth Tracker:"
  open_url "https://us.posthog.com/settings/user-api-keys"
  step "Create a personal API key with dashboard:read and query:read access"
  step "Make sure it can read project 196853, then copy it"
fi
ask_secret POSTHOG_PERSONAL_API_KEY "Paste the PostHog key (input hidden; Enter keeps current / skips):"
write_env PORT "$PORT"
write_env GITHUB_WEBHOOK_SECRET "$WEBHOOK_SECRET"
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
  write_env GITHUB_TOKEN "$GITHUB_TOKEN"
else
  SKIPPED+=("GITHUB_TOKEN in $ENV_TARGET — add it and: sudo systemctl restart pr-arcade")
fi
if [[ -n "${POSTHOG_PERSONAL_API_KEY:-}" ]]; then
  write_env POSTHOG_PERSONAL_API_KEY "$POSTHOG_PERSONAL_API_KEY"
else
  SKIPPED+=("POSTHOG_PERSONAL_API_KEY in $ENV_TARGET — the WAU panel will keep retrying")
fi
install_env_file
verify "$ENV_TARGET is 0600" \
  bash -c "[[ \"\$(stat -c %a $ENV_TARGET)\" == 600 ]]"
verify "webhook secret is in place" grep -q '^GITHUB_WEBHOOK_SECRET=' "$ENV_TARGET"
if [[ -n "${POSTHOG_PERSONAL_API_KEY:-}" ]]; then
  verify "PostHog key is in place" grep -q '^POSTHOG_PERSONAL_API_KEY=' "$ENV_TARGET"
fi
pause "Enter to install the services"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "systemd — server + kiosk"
say "Installing the two units: the server (restarts on crash, starts at boot)"
say "and the Chromium kiosk (starts with the desktop session)."
run "units installed and enabled" "$REPO_DIR/deploy/install.sh"
# --retry-connrefused: tsx takes a few seconds to compile and listen, so a bare
# curl right after `systemctl start` races it and fails a working install.
verify "server answers on localhost:$PORT" \
  curl -sf -o /dev/null --retry 15 --retry-delay 1 --retry-connrefused \
  "http://localhost:$PORT/"
verify "server service is running" systemctl is-active --quiet pr-arcade.service
verify "server starts at boot" systemctl is-enabled --quiet pr-arcade.service
verify "kiosk starts with the desktop session" \
  systemctl --user is-enabled --quiet pr-arcade-kiosk.service
verify "the board is reachable through the funnel" \
  curl -sf -o /dev/null "https://$TS_HOST/"
pause "Enter to register the webhooks"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GitHub webhooks — the Tracked Repos"
say "Each Tracked Repo needs a webhook pointing at the Pi. Settings → Webhooks"
say "→ Add webhook, with exactly these values:"
say ""
note "  Payload URL:   $WEBHOOK_URL"
note "  Content type:  application/json"
note "  Secret:        (the GITHUB_WEBHOOK_SECRET below)"
note "  SSL:           Enable SSL verification"
note "  Events:        'Let me select individual events' →"
note "                   Pull requests"
note "                   Pull request reviews"
note "                   Issue comments"
note "                   Workflow runs"
note "                 (untick everything else, including Pushes)"
say ""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 &&
   confirm "gh CLI is authed — register all ${#TRACKED_REPOS[@]} webhooks automatically?"; then
  # The hook config (url, events) and the secret are both sent every time. An
  # existing hook gets PATCHed rather than skipped: on a fresh secret, skipping
  # would leave GitHub signing with the old one and every real delivery 401ing
  # while this wizard's own test — signed with the new secret — looks green.
  # Body on stdin rather than -f flags: keeps the secret out of the process list.
  hook_body() {
    printf '{"active":true,"events":["pull_request","pull_request_review","issue_comment","workflow_run"],"config":{"url":"%s","content_type":"json","insecure_ssl":"0","secret":"%s"}}' \
      "$WEBHOOK_URL" "$WEBHOOK_SECRET"
  }
  for repo in "${TRACKED_REPOS[@]}"; do
    hook_id="$(gh api "repos/$repo/hooks" \
      --jq ".[] | select(.config.url == \"$WEBHOOK_URL\") | .id" 2>/dev/null | head -1)"
    if [[ -n "$hook_id" ]]; then
      if hook_body | gh api -X PATCH "repos/$repo/hooks/$hook_id" --input - >/dev/null; then
        ok "$repo — existing hook updated (secret + events refreshed)"
      else
        fail "$repo — couldn't update hook $hook_id"
        SKIPPED+=("webhook on $repo — update its secret by hand with the values above")
      fi
    elif hook_body | gh api "repos/$repo/hooks" --input - >/dev/null; then
      ok "$repo — hook created"
    else
      fail "$repo — couldn't create the hook (needs admin on the repo)"
      SKIPPED+=("webhook on $repo — add it by hand with the values above")
    fi
  done
else
  say "Add them by hand, using the values above. The pages:"
  for repo in "${TRACKED_REPOS[@]}"; do
    note "  https://github.com/$repo/settings/hooks/new"
  done
  say ""
  say "Secret to paste: $WEBHOOK_SECRET"
  if [[ "$SECRET_IS_NEW" == yes ]]; then
    say ""
    warn "This is a BRAND NEW secret. Any webhook that already exists on these"
    warn "repos is still signing with the old one and will 401 forever until you"
    warn "paste this secret into it — editing the existing hook, not adding another."
    SKIPPED+=("update the secret on any PRE-EXISTING webhook (it was regenerated this run)")
  fi
  say ""
  pause "Enter once all ${#TRACKED_REPOS[@]} are added"
  for repo in "${TRACKED_REPOS[@]}"; do
    if command -v gh >/dev/null 2>&1; then
      verify "$repo has a hook pointing here" \
        bash -c "gh api repos/$repo/hooks --jq '.[].config.url' | grep -qF '$WEBHOOK_URL'"
    else
      SKIPPED+=("verify webhook on $repo — check the green tick under Recent Deliveries")
    fi
  done
fi
pause "Enter for the end-to-end test"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "End-to-end test"
say "Sending a signed 'PR merged' delivery through the public funnel URL,"
say "exactly the way GitHub will. Watch the TV."
# Built from the configured list, not a test fixture: the fixture's repo is a
# placeholder, and an untracked repo is dropped on arrival — a green 204 with
# nothing on the TV, which reads as a display fault rather than a config one.
PAYLOAD="$(mktemp "${TMPDIR:-/tmp}/pr-arcade-payload.XXXXXX")"
printf '{"action":"closed","repository":{"full_name":"%s"},"pull_request":{"merged":true,"number":1,"title":"setup wizard smoke test","merged_by":{"login":"setup-wizard"}}}' \
  "${TRACKED_REPOS[0]}" >"$PAYLOAD"
SIG="$(sign_payload "$WEBHOOK_SECRET" "$PAYLOAD")"
CODE="$(curl -sS -o /dev/null -w '%{http_code}' \
  -X POST "$WEBHOOK_URL" \
  -H 'Content-Type: application/json' \
  -H 'X-GitHub-Event: pull_request' \
  -H "X-Hub-Signature-256: $SIG" \
  --data-binary "@$PAYLOAD" || echo 000)"
if [[ "$CODE" == 2* ]]; then
  ok "the funnel → server → display path works (HTTP $CODE)"
else
  fail "HTTP $CODE from $WEBHOOK_URL"
  note "  401 → the secret in $ENV_TARGET doesn't match the one you signed with"
  note "  502/000 → funnel or server down: tailscale funnel status; journalctl -u pr-arcade -n 50"
  SKIPPED+=("end-to-end webhook test (HTTP $CODE)")
fi
say ""
say "Now check an unsigned delivery is rejected:"
CODE="$(curl -sS -o /dev/null -w '%{http_code}' -X POST "$WEBHOOK_URL" \
  -H 'Content-Type: application/json' -d '{}' || echo 000)"
if [[ "$CODE" == 401 ]]; then ok "unsigned deliveries are rejected (401)"; else fail "expected 401, got $CODE"; fi
pause "Enter for the summary"

# Summary first: the reboot below never comes back to this terminal, so a
# skipped-steps list printed after it would never be read.
finish

if confirm "Reboot now to prove the whole thing comes up on its own?"; then
  say "Rebooting. Give it a minute, the TV should come back by itself."
  sudo reboot
fi
