#!/usr/bin/env node
// sync-kernel — compiles nextwork-kernel color tokens into public/kernel-tokens.gen.js
//
// Reads kernel/agent/visual/tokens/design-tokens.tailwind.css from the kernel/
// git submodule and emits every resolved --color-* token as a PixiJS integer
// (0xRRGGBB). Colors only — fonts, type scale, radii and spacing stay app-local.
//
// Usage:
//   npm run kernel:sync    # after bumping the kernel submodule; commit the result
//   npm run kernel:check   # exit 1 if the committed file drifted from the kernel
//
// The generated file is COMMITTED — never hand-edit it; this script is the only
// writer. syncedAt is the kernel HEAD commit date (not wall clock) so --check is
// a deterministic string compare.
//
// Exit codes: 0 in sync / 1 drift / 2 kernel submodule missing or unparseable.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const kernel = (p) => join(root, "kernel", p);
const OUT = join(root, "public", "kernel-tokens.gen.js");
const check = process.argv.includes("--check");

function fail(msg) {
  console.error(`[sync-kernel] FAIL: ${msg}`);
  process.exit(2);
}

if (!existsSync(kernel("agent/visual/tokens/design-tokens.tailwind.css"))) {
  fail("kernel submodule not initialised — run: git submodule update --init kernel");
}

// ── Parse colors ─────────────────────────────────────────────────────────────
const css = readFileSync(kernel("agent/visual/tokens/design-tokens.tailwind.css"), "utf8");
const raw = {};
for (const m of css.matchAll(/--color-([a-z0-9-]+):\s*(#[0-9a-fA-F]{6}|var\(--color-[a-z0-9-]+\))\s*;/g)) {
  raw[m[1]] = m[2];
}
if (Object.keys(raw).length < 50) fail(`only ${Object.keys(raw).length} color tokens parsed — CSS shape changed?`);
const colors = {};
for (const [name, value] of Object.entries(raw)) {
  let v = value;
  let hops = 0;
  while (v.startsWith("var(")) {
    const ref = v.match(/var\(--color-([a-z0-9-]+)\)/)?.[1];
    if (!ref || !(ref in raw)) fail(`unresolvable var ref for --color-${name}: ${v}`);
    v = raw[ref];
    if (++hops > 5) fail(`var() cycle at --color-${name}`);
  }
  colors[name] = v.toLowerCase();
}
// Every token the board's semantic layer (C in client.js) depends on.
const MUST_EXIST = [
  "paper", "leather", "warm-white",
  "brand-600", "brand-700", "brand-800", "brand-900",
  "surface-dark", "surface-dark-raised", "text-on-dark", "text-on-dark-muted",
  "accent-canary", "accent-emerald", "accent-pumpkin",
  "error-400", "plum-400", "information-400",
];
for (const must of MUST_EXIST) {
  if (!colors[must]) fail(`expected token missing: ${must}`);
}

// ── Meta + emit ──────────────────────────────────────────────────────────────
const sha = execSync("git -C kernel rev-parse --short HEAD", { cwd: root }).toString().trim();
const changelog = readFileSync(kernel("CHANGELOG.md"), "utf8");
const version = changelog.match(/^## (v[\d.]+)/m)?.[1] ?? "unknown";
const syncedAt = execSync("git -C kernel show -s --format=%cs HEAD", { cwd: root }).toString().trim();

const next = `// GENERATED by scripts/sync-kernel.mjs — DO NOT EDIT BY HAND.
// Source: nextwork-kernel @ ${sha} (${version}), kernel commit date ${syncedAt}.
// Pixi wants integer colors, so #rrggbb becomes 0xrrggbb here in the generator.
// To update: bump the kernel/ submodule, then \`npm run kernel:sync\`.

export const KERNEL_META = ${JSON.stringify({ sha, version, syncedAt }, null, 2)};

export const KERNEL = {
${Object.entries(colors)
  .map(([name, hex]) => `  "${name}": 0x${hex.slice(1)},`)
  .join("\n")}
};
`;

if (check) {
  const cur = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (cur.trim() !== next.trim()) {
    console.error("[sync-kernel] kernel-tokens.gen.js is OUT OF SYNC with the kernel submodule.");
    console.error("Run: npm run kernel:sync  (then commit the regenerated file).");
    process.exit(1);
  }
  console.log(`[sync-kernel] in sync — ${Object.keys(colors).length} colors ← kernel ${sha} (${version})`);
} else {
  writeFileSync(OUT, next);
  console.log(`[sync-kernel] OK — ${Object.keys(colors).length} colors → public/kernel-tokens.gen.js ← kernel ${sha} (${version})`);
}
